export const chakraData = [
  {
    id: 1,
    name: "Root",
    sanskrit: "Muladhara",
    color: "#FF3B30",
    glow: "rgba(255, 59, 48, 0.6)",
    meaning: "Grounding, Security, Survival",
    icon: "🔴",
  },
  {
    id: 2,
    name: "Sacral",
    sanskrit: "Svadhisthana",
    color: "#FF9500",
    glow: "rgba(255, 149, 0, 0.6)",
    meaning: "Creativity, Emotions, Passion",
    icon: "🟠",
  },
  {
    id: 3,
    name: "Solar Plexus",
    sanskrit: "Manipura",
    color: "#FFCC00",
    glow: "rgba(255, 204, 0, 0.6)",
    meaning: "Power, Will, Confidence",
    icon: "🟡",
  },
  {
    id: 4,
    name: "Heart",
    sanskrit: "Anahata",
    color: "#00E676", // Using brand green
    glow: "rgba(0, 230, 118, 0.6)",
    meaning: "Love, Compassion, Healing",
    icon: "🟢",
  },
  {
    id: 5,
    name: "Throat",
    sanskrit: "Vishuddha",
    color: "#34A853",
    glow: "rgba(52, 168, 83, 0.6)",
    meaning: "Communication, Truth",
    icon: "🔵",
  },
  {
    id: 6,
    name: "Third Eye",
    sanskrit: "Ajna",
    color: "#5B6ABF",
    glow: "rgba(91, 106, 191, 0.6)",
    meaning: "Intuition, Imagination, Wisdom",
    icon: "🟣",
  },
  {
    id: 7,
    name: "Crown",
    sanskrit: "Sahasrara",
    color: "#AF52DE",
    glow: "rgba(175, 82, 222, 0.6)",
    meaning: "Spirituality, Awareness",
    icon: "✨",
  },
];
