export const suryaNamaskarFlow = [
  {
    phase: "01",
    sanskritName: "Pranamasana",
    name: "Prayer Pose",
    description: "Stand at the edge of your mat, keep your feet together and balance your weight equally on both feet.",
    breathing: "Exhale",
    icon: "🙏",
  },
  {
    phase: "02",
    sanskritName: "Hasta Uttanasana",
    name: "Raised Arms Pose",
    description: "Lift your arms up and back, keeping the biceps close to the ears, stretching the whole body.",
    breathing: "Inhale",
    icon: "🙌",
  },
  {
    phase: "03",
    sanskritName: "Padahastasana",
    name: "Hand to Foot Pose",
    description: "Bend forward from the waist, keeping the spine erect. Exhale and bring hands down to the floor.",
    breathing: "Exhale",
    icon: "🙇",
  },
  {
    phase: "04",
    sanskritName: "Ashwa Sanchalanasana",
    name: "Equestrian Pose",
    description: "Push your right leg back as far as possible, drop the right knee to the floor, and look up.",
    breathing: "Inhale",
    icon: "🐎",
  },
  {
    phase: "05",
    sanskritName: "Dandasana",
    name: "Stick Pose",
    description: "Bring the left leg back to meet the right, keeping your body in a straight line.",
    breathing: "Exhale",
    icon: "🧘",
  },
  {
    phase: "06",
    sanskritName: "Ashtanga Namaskara",
    name: "Eight Limbed Salutation",
    description: "Gently bring your knees down to the floor, followed by your chest and chin.",
    breathing: "Hold Breath",
    icon: "🙇‍♀️",
  },
  {
    phase: "07",
    sanskritName: "Bhujangasana",
    name: "Cobra Pose",
    description: "Slide forward and raise the chest up, looking up towards the ceiling.",
    breathing: "Inhale",
    icon: "🐍",
  },
  {
    phase: "08",
    sanskritName: "Adho Mukha Svanasana",
    name: "Downward Facing Dog",
    description: "Lift the hips and tailbone up, bringing the body into an inverted 'V' shape.",
    breathing: "Exhale",
    icon: "🐕",
  },
  {
    phase: "09",
    sanskritName: "Ashwa Sanchalanasana",
    name: "Equestrian Pose",
    description: "Bring the right foot forward between the two hands, left knee down to the floor, look up.",
    breathing: "Inhale",
    icon: "🐎",
  },
  {
    phase: "10",
    sanskritName: "Padahastasana",
    name: "Hand to Foot Pose",
    description: "Bring the left foot forward. Keep the palms on the floor and bend forward.",
    breathing: "Exhale",
    icon: "🙇",
  },
  {
    phase: "11",
    sanskritName: "Hasta Uttanasana",
    name: "Raised Arms Pose",
    description: "Roll the spine up, raise arms up and bend backward slightly.",
    breathing: "Inhale",
    icon: "🙌",
  },
  {
    phase: "12",
    sanskritName: "Tadasana",
    name: "Mountain Pose",
    description: "Straighten the body, bring the arms down, and relax in a neutral standing position.",
    breathing: "Exhale",
    icon: "🧍",
  },
];
