import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

const initialState = {
  currentPlan: null,       // The plan currently being generated or viewed
  generatedPlans: [],      // All plans generated by the user
  activeSession: null,     // Details if a session is currently actively playing
  wellnessPreferences: {   // Global user preferences
    favoriteInstructors: [],
    preferredDurations: [],
    goals: []
  },
  recentActivity: [],      // Log of recent user actions (e.g., completed a phase)
  generatedHistory: [],    // Historical log of sessions
};

export const useWellnessStore = create(
  persist(
    (set, get) => ({
      ...initialState,

      // Plan Actions
      setCurrentPlan: (plan) => set({ currentPlan: plan }),
      
      saveGeneratedPlan: (plan) => set((state) => {
        // Prevent duplicates
        const exists = state.generatedPlans.find(p => p.id === plan.id);
        if (exists) return state;
        
        return {
          generatedPlans: [plan, ...state.generatedPlans]
        };
      }),

      updatePlanProgress: (planId, progress) => set((state) => ({
        generatedPlans: state.generatedPlans.map(plan => 
          plan.id === planId ? { ...plan, progress, lastOpenedAt: new Date().toISOString() } : plan
        )
      })),

      // Session Actions
      setActiveSession: (sessionDetails) => set({ activeSession: sessionDetails }),
      
      clearActiveSession: () => set({ activeSession: null }),

      // History Actions
      addHistoryLog: (logEntry) => set((state) => ({
        generatedHistory: [logEntry, ...state.generatedHistory]
      })),

      addRecentActivity: (activity) => set((state) => {
        const newActivity = [activity, ...state.recentActivity];
        // Keep only last 10 activities to prevent bloat
        return { recentActivity: newActivity.slice(0, 10) };
      }),

      // Preferences Actions
      updatePreferences: (prefs) => set((state) => ({
        wellnessPreferences: { ...state.wellnessPreferences, ...prefs }
      })),

      // Reset
      resetStore: () => set(initialState)
    }),
    {
      name: 'yogawomans-wellness-storage', // key in local storage
      storage: createJSONStorage(() => localStorage),
      // Optional: partalize can be used to omit certain state from persistence
      partialize: (state) => ({ 
        generatedPlans: state.generatedPlans,
        wellnessPreferences: state.wellnessPreferences,
        recentActivity: state.recentActivity,
        generatedHistory: state.generatedHistory,
        // We might choose NOT to persist activeSession if it should reset on reload,
        // but persisting it allows seamless journey continuation. Let's persist it.
        activeSession: state.activeSession,
        currentPlan: state.currentPlan
      }),
    }
  )
);
